/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Concepto;
import Recibo.recibo;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Jacky
 */
public class MantenimientoConcepto extends javax.swing.JFrame {

    /**
     * Creates new form MantenimientoConcepto
     */
    public MantenimientoConcepto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtid1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtnombres1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        a = new javax.swing.JRadioButton();
        b = new javax.swing.JRadioButton();
        aviso = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtnaturaleza = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txttipo = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtsueldo2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtsueldoextra2 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtcomis2 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        txtboni = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtotross2 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtanticipos = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtjudicial = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        txtotrosss = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txtinicial = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtfinal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        Buscar2 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        registro = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setText("Ingrese el Id del Empleado que desea buscar");

        jLabel40.setBackground(new java.awt.Color(204, 255, 204));
        jLabel40.setText("id_Empleado:");

        jLabel41.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(153, 0, 0));
        jLabel41.setText("Concepto");

        jLabel39.setBackground(new java.awt.Color(204, 255, 204));
        jLabel39.setText("Nombre Empleado");

        txtnombres1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel38.setBackground(new java.awt.Color(204, 255, 204));
        jLabel38.setText("Estatus:");

        a.setText("Activo");

        b.setText("Inactivo");

        jLabel37.setBackground(new java.awt.Color(204, 255, 204));
        jLabel37.setText("Naturaleza:");

        jLabel36.setBackground(new java.awt.Color(204, 255, 204));
        jLabel36.setText("Tipo:");

        jLabel34.setBackground(new java.awt.Color(204, 255, 204));
        jLabel34.setText("Aplicacion de conceptos:");

        jLabel35.setText("jLabel13");

        jLabel42.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel42.setText("Sueldo Ordinario:");

        jLabel43.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel43.setText("Sueldo Extraordinario:");

        txtsueldoextra2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel44.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel44.setText("Comisiones:");

        txtcomis2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel53.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel53.setText("Bonificacion:");

        jLabel45.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel45.setText("Otros:");

        txtotross2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel48.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel48.setText("DESCUENTOS");

        jLabel47.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel47.setText("Anticipos:");

        txtanticipos.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel46.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel46.setText("Descuento Judicial:");

        txtjudicial.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        jLabel51.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(153, 0, 0));
        jLabel51.setText("Nomina");

        jLabel52.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel52.setText("Otros:");

        txtotrosss.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        txtotrosss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotrosssActionPerformed(evt);
            }
        });

        jLabel50.setText("Fecha inicial");

        jLabel49.setText("Fecha final");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Empleado", "Nombre Empleado", "Estatus", "Naturaleza", "Tipo", "Sueldo Ordinario", "Sueldo Extraordinario", "Comisiones", "Bonificacion", "Otos Ingresos", "Total Ingresos", "Anticipos", "Descuento Judicial", "IGSS", "ISR", "Otros Descuentos", "Total Egresos", "Fecha inicial", "Fecha final", "Sueldo Liquido"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        Buscar2.setText("Buscar");
        Buscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar2ActionPerformed(evt);
            }
        });

        jButton16.setText("Ingresar a la Tabla");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton1.setText("Colocar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        registro.setBackground(new java.awt.Color(204, 255, 255));
        registro.setText("Registrar Empleados a la base de datos");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Buscar2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel34)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel38)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtid1)
                                            .addComponent(txtnombres1)
                                            .addComponent(txtnaturaleza, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel35)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(a)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(b)
                                        .addGap(18, 18, 18)
                                        .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel42)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtsueldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel44)
                                                    .addComponent(jLabel43)
                                                    .addComponent(jLabel45))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtsueldoextra2)
                                                    .addComponent(txtcomis2)
                                                    .addComponent(txtotross2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(jLabel53)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtboni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(82, 82, 82)
                                                    .addComponent(jLabel48))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel46)
                                                        .addComponent(jLabel47))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtanticipos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtjudicial, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel50)
                                                        .addComponent(jLabel49))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtfinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel52)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtotrosss, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton16)
                        .addGap(311, 311, 311))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(registro)
                        .addGap(18, 18, 18)
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Eliminar)
                        .addGap(212, 212, 212))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel47)
                                    .addComponent(txtanticipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel46)
                                    .addComponent(txtjudicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtotrosss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel52))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel50)
                                    .addComponent(txtinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsueldo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel42))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel43)
                                    .addComponent(txtsueldoextra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcomis2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtboni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel53))
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(txtfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtotross2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45)))
                    .addComponent(jLabel51)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(txtnombres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(a)
                            .addComponent(b)
                            .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(txtnaturaleza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(txttipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34))))
                .addGap(35, 35, 35)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtotrosssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotrosssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotrosssActionPerformed

    private void Buscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar2ActionPerformed
        //Codigo que sirve para buscar a la persona en la base de datos
        // Codigo para buscar datos en la base de datos:
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from concepto where id_empleado = ?");
            pst.setString(1, txtBuscar.getText().trim());
            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                txtid1.setText(rs.getString("id_empleado"));
                txtnombres1.setText(rs.getString("nombre_empleado"));
                aviso.setText(rs.getString("estatus"));
                txtnaturaleza.setText(rs.getString("naturaleza"));
                txttipo.setText(rs.getString("tipo"));
                txtsueldo2.setText(rs.getString("sueldo_ordinario"));
                txtsueldoextra2.setText(rs.getString("sueldo_extraordinario"));
                txtcomis2.setText(rs.getString("comisiones"));
                txtboni.setText(rs.getString("bonificaciones"));
                txtotross2.setText(rs.getString("otros_ingresos"));
                txtanticipos.setText(rs.getString("anticipos"));
                txtjudicial.setText(rs.getString("descuento_judicial"));
                txtotrosss.setText(rs.getString("otros_descuentos"));
                txtinicial.setText(rs.getString("fecha_inicial"));
                txtfinal.setText(rs.getString("fecha_final"));

            } else {
                JOptionPane.showMessageDialog(null, "Persona no registrada.");
            }

        }catch (Exception e){

        }
    }//GEN-LAST:event_Buscar2ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        //Codigo echo por Jaqueline Carrera
        //Codigo que ingresa los datos a la tabla con sus respectivas condiciones
        //Se empiezan a poner las variables para los txtfield
        String Id=txtid1.getText(),Nombre=txtnombres1.getText(),Natu=txtnaturaleza.getText();
        String Tip=txttipo.getText();
        String fechai=txtinicial.getText();
        String fechaf=txtfinal.getText();
        String selec;
        selec = aviso.getText();

        float SueldoO=Float.parseFloat(txtsueldo2.getText());
        float SueldoE=Float.parseFloat(txtsueldoextra2.getText());
        float comisiones=Float.parseFloat(txtcomis2.getText());
        float bonificaciones=Float.parseFloat(txtcomis2.getText());
        float Otrosi=Float.parseFloat(txtotross2.getText());
        float TotalIngresos;
        float anticipos=Float.parseFloat(txtanticipos.getText());
        float Desc=Float.parseFloat(txtjudicial.getText());
        float Otrosd=Float.parseFloat(txtotrosss.getText());
        float igss1;
        float isr1 = 0;
        float TotalEgresos;
        float SueldoLiquido;
        //Condicion del ISR para sueldos mayores de 5000
        if(SueldoO>=5000){
            isr1=(float) (SueldoO*0.0145);
        }
        //Calculos del IGSS, Total ingresos, Total Egresos y Sueldo Liquido
        igss1= (float) (SueldoO*0.0483);
        TotalIngresos=(SueldoO+SueldoE+comisiones+Otrosi);
        TotalEgresos=(anticipos+Desc+Otrosd+igss1+isr1);
        SueldoLiquido=(TotalIngresos-TotalEgresos);
        //Datos que se iran a la tabla
        DefaultTableModel modelo=(DefaultTableModel)
        tabla.getModel();
        Object [] fila=new  Object[20];
        fila[0]=Id;
        fila[1]=Nombre;
        fila[2]=selec;
        fila[3]=Natu;
        fila[4]=Tip;
        fila[5]=SueldoO;
        fila[6]=SueldoE;
        fila[7]=comisiones;
        fila[8]=bonificaciones;
        fila[9]=Otrosi;
        fila[10]=TotalIngresos;
        fila[11]=anticipos;
        fila[12]=Desc;
        fila[13]=igss1;
        fila[14]=isr1;
        fila[15]=Otrosd;
        fila[16]=TotalEgresos;
        fila[17]=fechai;
        fila[18]=fechaf;
        fila[19]=SueldoLiquido;
        modelo.addRow(fila);
        tabla.setModel(modelo);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //Condicion para los buttoncheck Jaqueline Carrera
        String selec="";

        if (a.isSelected())     {
            selec= "Activo";   }
        if (b.isSelected())     {
            selec= "Inactivo";   }
        aviso.setText(selec);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed

        // Codigo que ingresa
        //Jaqueline Carrera
        try{
            for(int i=0; i<tabla.getRowCount();++i)// se Ingresaran los datos de la tabla

            {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/nomina", "root", "");//conecta a MYSQL
                PreparedStatement pst = cn.prepareStatement("insert into concepto values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

                pst.setString(1, tabla.getValueAt(i,0).toString());//Codigo para ingresar datos desde la tabla
                pst.setString(2, tabla.getValueAt(i,1).toString());
                pst.setString(3, tabla.getValueAt(i,2).toString());
                pst.setString(4, tabla.getValueAt(i,3).toString());
                pst.setString(5, tabla.getValueAt(i,4).toString());
                pst.setString(6, tabla.getValueAt(i,5).toString());
                pst.setString(7, tabla.getValueAt(i,6).toString());
                pst.setString(8, tabla.getValueAt(i,7).toString());
                pst.setString(9, tabla.getValueAt(i,8).toString());
                pst.setString(10, tabla.getValueAt(i,9).toString());
                pst.setString(11, tabla.getValueAt(i,10).toString());
                pst.setString(12, tabla.getValueAt(i,11).toString());
                pst.setString(13, tabla.getValueAt(i,12).toString());
                pst.setString(14, tabla.getValueAt(i,13).toString());
                pst.setString(15, tabla.getValueAt(i,14).toString());
                pst.setString(16, tabla.getValueAt(i,15).toString());
                pst.setString(17, tabla.getValueAt(i,16).toString());
                pst.setString(18, tabla.getValueAt(i,17).toString());
                pst.setString(19, tabla.getValueAt(i,18).toString());
                pst.setString(20, tabla.getValueAt(i,19).toString());
                pst.executeUpdate();

                label1.setText("Se registraron los empleados");
            }

        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_registroActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed

        // Codigo que modifica
        //Jaqueline Carrera
        try{
            for(int i=0; i<tabla.getRowCount();++i)// se Ingresaran los datos de la tabla

            {
                String ID = txtBuscar.getText().trim();
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/nomina", "root", "");//conecta a MYSQL
                PreparedStatement pst = cn.prepareStatement("update concepto set nombre_empleado = ?, estatus = ?, naturaleza = ?, tipo = ?, sueldo_ordinario = ?,sueldo_extraordinario = ?, comisiones = ?, bonificaciones = ?, otros_ingresos = ?, total_ingresos = ?,anticipos = ?, descuento_judicial = ?, igss = ?, isr = ?,otros_descuentos = ?,total_egresos = ?, fecha_inicial = ?, fecha_final = ?, sueldo_liquido = ? where id_empleado = "+ ID);

                pst.setString(1, tabla.getValueAt(i,0).toString());//Codigo para ingresar datos desde la tabla
                pst.setString(2, tabla.getValueAt(i,1).toString());
                pst.setString(3, tabla.getValueAt(i,2).toString());
                pst.setString(4, tabla.getValueAt(i,3).toString());
                pst.setString(5, tabla.getValueAt(i,4).toString());
                pst.setString(6, tabla.getValueAt(i,5).toString());
                pst.setString(7, tabla.getValueAt(i,6).toString());
                pst.setString(8, tabla.getValueAt(i,7).toString());
                pst.setString(9, tabla.getValueAt(i,8).toString());
                pst.setString(10, tabla.getValueAt(i,9).toString());
                pst.setString(11, tabla.getValueAt(i,10).toString());
                pst.setString(12, tabla.getValueAt(i,11).toString());
                pst.setString(13, tabla.getValueAt(i,12).toString());
                pst.setString(14, tabla.getValueAt(i,13).toString());
                pst.setString(15, tabla.getValueAt(i,14).toString());
                pst.setString(16, tabla.getValueAt(i,15).toString());
                pst.setString(17, tabla.getValueAt(i,16).toString());
                pst.setString(18, tabla.getValueAt(i,17).toString());
                pst.setString(19, tabla.getValueAt(i,18).toString());
                pst.setString(20, tabla.getValueAt(i,19).toString());
                pst.executeUpdate();

                label1.setText("Se Modifico");

            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // Codigo para eliminar en la base de datos
        //
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nomina", "root", "");
            PreparedStatement pst = cn.prepareStatement("delete from concepto where id_empleado = ?");

            pst.setString(1, txtBuscar.getText().trim());
            pst.executeUpdate();

            txtid1.setText("");
            txtnombres1.setText("");
            aviso.setText("");
            txtnaturaleza.setText("");
            txttipo.setText("");
            txtsueldo2.setText("");
            txtsueldoextra2.setText("");
            txtcomis2.setText("");
            txtboni.setText("");
            txtotross2.setText("");
            txtanticipos.setText("");
            txtjudicial.setText("");
            txtotrosss.setText("");
            txtinicial.setText("");
            txtfinal.setText("");
            label1.setText("Registro eliminado.");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoConcepto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar2;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Modificar;
    private javax.swing.JRadioButton a;
    private javax.swing.JTextField aviso;
    private javax.swing.JRadioButton b;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JButton registro;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtanticipos;
    private javax.swing.JTextField txtboni;
    private javax.swing.JTextField txtcomis2;
    private javax.swing.JTextField txtfinal;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtinicial;
    private javax.swing.JTextField txtjudicial;
    private javax.swing.JTextField txtnaturaleza;
    private javax.swing.JTextField txtnombres1;
    private javax.swing.JTextField txtotross2;
    private javax.swing.JTextField txtotrosss;
    private javax.swing.JTextField txtsueldo2;
    private javax.swing.JTextField txtsueldoextra2;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
