//DIANA VICTORES 9959-19-1471/CODIGO Y DISEÑO
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CONTENEDOR;

import Mantenimientos.Almacenamiento_Departamento;
import Mantenimientos.Almacenamientodeempleados;
import Mantenimientos.Almacenamientodepuestos;
import Nomina.LABORATORIO1;
import Nomina.bitacora;
import Nomina.r_empleados;
import Recibo.recibo;
//import Nomina.nomina_exe;
import modelo.Usuarios;

/**
 *
 * @author Diana
 */
public class Contenedor extends javax.swing.JFrame {
    Usuarios mod;
    /**
     * Creates new form Contenedor
     */
    public Contenedor() {
        initComponents();
    }
    public Contenedor (Usuarios mod){
    initComponents();
        setLocationRelativeTo(null);
        this.mod = mod;
        
        if (mod.getIdTipo() == 1) {
            MANTENIMIENTOS.setVisible(true);
           NOMINA.setVisible(true);
        } else {
             MANTENIMIENTOS.setVisible(false);
            NOMINA.setVisible(false);
        }

    }
    
       
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MANTENIMIENTOS = new javax.swing.JMenu();
        jCheckBoxMenuItem10 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem9 = new javax.swing.JCheckBoxMenuItem();
        NOMINA = new javax.swing.JMenu();
        jCheckBoxMenuItem6 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        SALIR = new javax.swing.JMenu();
        jCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CONTENEDOR/blue3.jpg"))); // NOI18N

        MANTENIMIENTOS.setForeground(new java.awt.Color(0, 0, 204));
        MANTENIMIENTOS.setText("Mantenimientos ");
        MANTENIMIENTOS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MANTENIMIENTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MANTENIMIENTOSActionPerformed(evt);
            }
        });

        jCheckBoxMenuItem10.setSelected(true);
        jCheckBoxMenuItem10.setText("Mantenimiento Empleados");
        jCheckBoxMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem10ActionPerformed(evt);
            }
        });
        MANTENIMIENTOS.add(jCheckBoxMenuItem10);

        jCheckBoxMenuItem8.setSelected(true);
        jCheckBoxMenuItem8.setText("Mantenimiento Departamentos");
        jCheckBoxMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem8ActionPerformed(evt);
            }
        });
        MANTENIMIENTOS.add(jCheckBoxMenuItem8);

        jCheckBoxMenuItem9.setSelected(true);
        jCheckBoxMenuItem9.setText("Mantenimiento Puestos");
        jCheckBoxMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem9ActionPerformed(evt);
            }
        });
        MANTENIMIENTOS.add(jCheckBoxMenuItem9);

        jMenuBar1.add(MANTENIMIENTOS);

        NOMINA.setForeground(new java.awt.Color(255, 0, 0));
        NOMINA.setText("NOMINA");
        NOMINA.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jCheckBoxMenuItem6.setSelected(true);
        jCheckBoxMenuItem6.setText("Planilla");
        jCheckBoxMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem6ActionPerformed(evt);
            }
        });
        NOMINA.add(jCheckBoxMenuItem6);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Registro Empleados");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        NOMINA.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Bitacora");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        NOMINA.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Recibo");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        NOMINA.add(jCheckBoxMenuItem3);

        jMenuBar1.add(NOMINA);

        SALIR.setForeground(new java.awt.Color(51, 153, 0));
        SALIR.setText("SALIR");
        SALIR.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("Salir del Sistema");
        jCheckBoxMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem5ActionPerformed(evt);
            }
        });
        SALIR.add(jCheckBoxMenuItem5);

        jMenuBar1.add(SALIR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jCheckBoxMenuItem5ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // REGISTRO EMPLEADOS
        
         r_empleados frm = new r_empleados();
         frm.setVisible(true);
         this.setVisible(false);
        

    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // BITACORA
        
        
         bitacora frm = new bitacora();
         frm.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        // RECIBO
        
         recibo frm = new recibo();
         frm.setVisible(true);
         this.setVisible(false);
        
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void jCheckBoxMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem6ActionPerformed
        // Planilla
         LABORATORIO1 frm = new LABORATORIO1();
         frm.setVisible(true);
         this.setVisible(false);
      
        
    }//GEN-LAST:event_jCheckBoxMenuItem6ActionPerformed

    private void jCheckBoxMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem9ActionPerformed
        // MANTENIMIENTO DE PUESTOS
        
        
       Almacenamientodepuestos frm = new Almacenamientodepuestos();
         frm.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jCheckBoxMenuItem9ActionPerformed

    private void jCheckBoxMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem8ActionPerformed
        // TODO add your handling code here:
        
       Almacenamiento_Departamento frm = new Almacenamiento_Departamento();
         frm.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jCheckBoxMenuItem8ActionPerformed

    private void jCheckBoxMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem10ActionPerformed
        // ALMACENAMIENTO EMPLEADOS
 Almacenamientodeempleados frm = new Almacenamientodeempleados();
         frm.setVisible(true);
         this.setVisible(false);
//         
    }//GEN-LAST:event_jCheckBoxMenuItem10ActionPerformed

    private void MANTENIMIENTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MANTENIMIENTOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MANTENIMIENTOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MANTENIMIENTOS;
    private javax.swing.JMenu NOMINA;
    private javax.swing.JMenu SALIR;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem10;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem6;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    private static class usuarios {

        public usuarios() {
        }
    }

    private static class NOMINA {

        private static void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public NOMINA() {
        }
    }
}
